# Generated by Django 4.0.6 on 2022-07-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currency_title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
