# Generated by Django 4.0.6 on 2022-07-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_currency_currency_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
