# Generated by Django 4.0.6 on 2022-07-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_price_price_ask_alter_price_price_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='api.city'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='api.currency'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='api.place'),
        ),
    ]
