# Generated by Django 4.0.6 on 2022-07-11 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_price_price_city_alter_price_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_last_updates',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
