# Generated by Django 4.0.6 on 2022-09-23 13:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='City name')),
                ('title', models.CharField(max_length=128, verbose_name='City title')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='Currency name')),
                ('title', models.CharField(max_length=64, verbose_name='Currency title')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_price_ask', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bank price ask')),
                ('bank_price_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bank price bid')),
                ('exchanger_price_ask', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Exchanger price ask')),
                ('exchanger_price_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Exchanger price bid')),
                ('nbu_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='NBU price')),
                ('parser_status', models.BooleanField(default=False, verbose_name='Parser status')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last update')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='parser.city', verbose_name='City')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='parser.currency', verbose_name='Currency')),
            ],
            options={
                'ordering': ('last_update',),
            },
        ),
    ]
