# Generated by Django 4.0.6 on 2022-09-24 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US dollar'), ('EUR', 'Euro'), ('PLN', 'Polish zloty'), ('AUD', 'Australian dollar'), ('NOK', 'Norwegian krone'), ('DKK', 'Danish krone'), ('CAD', 'Canadian dollar'), ('CNY', 'Chinese yuan renminbi'), ('TRY', 'Turkish lira'), ('JPY', 'Japanese yen'), ('ILS', 'Israeli shekel'), ('CHF', 'Swiss franc'), ('GBP', 'Pound sterling'), ('SEK', 'Swedish krona')], max_length=64, verbose_name='Currency')),
                ('city', models.CharField(choices=[('LV', 'Lviv'), ('KY', 'Kyiv')], max_length=64, verbose_name='City')),
                ('place', models.CharField(choices=[('BA', 'Banks'), ('EX', 'Exchanger'), ('MA', 'Market')], max_length=64, verbose_name='Place')),
                ('price_ask', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price ask')),
                ('price_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price bid')),
                ('parser_status', models.BooleanField(default=True, verbose_name='Parser status')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last update')),
            ],
            options={
                'ordering': ('-last_update',),
            },
        ),
    ]
