# Generated by Django 4.0.6 on 2022-09-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='bank_price_ask',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bank price ask'),
        ),
        migrations.AlterField(
            model_name='price',
            name='bank_price_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bank price bid'),
        ),
        migrations.AlterField(
            model_name='price',
            name='exchanger_price_ask',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Exchanger price ask'),
        ),
        migrations.AlterField(
            model_name='price',
            name='exchanger_price_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Exchanger price bid'),
        ),
        migrations.AlterField(
            model_name='price',
            name='nbu_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='NBU price'),
        ),
    ]
